// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Equipo de Microservicios",
            "email": "soporte@empresa.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Verifica que el servicio de reportes está activo y operativo.",
                "produces": ["application/json"],
                "tags": ["Diagnóstico"],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Servicio operativo",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        },
        "/reportes/resumen": {
            "get": {
                "description": "Consulta los servicios de empleados y departamentos para generar un resumen estadístico del sistema.",
                "produces": ["application/json"],
                "tags": ["Reportes"],
                "summary": "Obtener resumen del sistema",
                "responses": {
                    "200": {
                        "description": "Resumen estadístico generado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/main.ResumenResponse"
                        }
                    },
                    "500": {
                        "description": "Error al consultar uno o más servicios",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "example": "ok"},
                "service": {"type": "string", "example": "reportes-service"},
                "version": {"type": "string", "example": "1.0.0"},
                "docs": {"type": "string", "example": "/docs/index.html"}
            }
        },
        "main.ResumenResponse": {
            "type": "object",
            "properties": {
                "totalDepartamentos": {"type": "integer", "example": 5},
                "totalEmpleados": {"type": "integer", "example": 20},
                "fechaConsulta": {"type": "string", "format": "date-time"},
                "fuenteEmpleados": {"type": "string", "example": "http://empleados-service:8000"},
                "fuenteDepartamentos": {"type": "string", "example": "http://departamentos-service:8000"}
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string", "example": "Error de comunicación"},
                "detail": {"type": "string", "example": "No se pudo contactar el servicio de empleados"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Servicio de Reportes",
	Description:      "Microservicio de Reportes - Genera estadísticas del sistema consultando los demás microservicios.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
