# =====================================================
# SonarQube — Configuración para departamentos-service
# =====================================================
# Lenguaje: Java 17 (Spring Boot 3)
# Cobertura: JaCoCo
# =====================================================

sonar.projectKey=departamentos-service
sonar.projectName=Departamentos Service
sonar.projectVersion=1.1.0

# Código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Lenguaje
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.source=17

# Cobertura JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones
sonar.exclusions=**/dto/**,**/model/**,**/exception/**,**/config/**

# Servidor SonarQube
sonar.host.url=http://sonarqube:9000
